### ISSUE TITLE
Copyright (c) 2004-2006 Nokia Corporation?

### ISSUE THREAD

**Issue by Pomax** [Dante-Leoncini/Blendersito#1]
Just checking: are you sure you have the rights to redistribute this?

**Comment by Dante-Leoncini** [comment]
I used as a base the most basic example of Nokia, The one of a cube with openGl. The code was rewritten so many times that only the minimum and necessary to make it work remained. I'm sure it won't be a problem. Just in case remove Nokia comments from the files I redid. just leave them in utilities.
________________________________
De: Pomax ***@***.***>
Enviado: sábado, 14 de enero de 2023 15:13
Para: Dante-Leoncini/Blendersito ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [Dante-Leoncini/Blendersito] Copyright (c) 2004-2006 Nokia Corporation? (Issue #1)


Just checking: are you sure you have the rights to redistribute this?
