### ISSUE TITLE
Prueba en nokia E90

### ISSUE THREAD

**Issue by chrisgomez36** [Dante-Leoncini/Blendersito#2]
Una pruebita en el nokia E90
![IMG_20240508_230321_682](https://github.com/Dante-Leoncini/Blendersito/assets/141393232/0c42cdd9-5579-42c4-97ad-3cc29db82378)

**Comment by Dante-Leoncini** [comment]
se ve hermoso. me alegra que se adapte bien a la pantalla

**Comment by Dante-Leoncini** [comment]
ah. y el teclado tendria que funcionar igual que en el blender original. g para mover, r, para rotar, s para escalar. luego x,y,z para cambiar el eje de transformacion. etc etc
